'use client'

import Link from 'next/link'
import PageNav from '@/components/PageNav'

export default function TermsPage() {
  return (
    <div className="min-h-screen">
      <div className="max-w-2xl mx-auto px-4 py-8">
        <PageNav />

        <article className="prose prose-gray max-w-none">
          <h1 className="text-3xl font-semibold text-gray-900 mb-2">Terms of Service</h1>
          <p className="text-sm text-gray-400 mb-8">Last updated: January 2026</p>
          
          <p className="text-gray-600 leading-relaxed mb-6">
            By using HumansOnly, you agree to these terms. Please read them carefully.
          </p>

          <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">1. Eligibility</h2>
          <p className="text-gray-600 leading-relaxed mb-6">
            You must be at least 13 years old to use HumansOnly. You must be a human being.
            Automated accounts, bots, and AI agents are not permitted.
          </p>

          <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">2. Your account</h2>
          <p className="text-gray-600 leading-relaxed mb-6">
            You are responsible for keeping your account secure. Do not share your password.
            You are responsible for all activity on your account.
          </p>

          <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">3. Content rules</h2>
          <ul className="text-gray-600 space-y-2 mb-6">
            <li>Do not post illegal content</li>
            <li>Do not harass or threaten other users</li>
            <li>Do not spam or post repetitive content</li>
            <li>Do not impersonate others</li>
            <li>Do not post content generated by AI</li>
          </ul>

          <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">4. Your content</h2>
          <p className="text-gray-600 leading-relaxed mb-6">
            You own the content you post. By posting, you grant us a license to display it 
            on the platform. You can delete your content at any time.
          </p>

          <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">5. Termination</h2>
          <p className="text-gray-600 leading-relaxed mb-6">
            We may suspend or terminate accounts that violate these terms. You can delete 
            your account at any time.
          </p>

          <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">6. Disclaimer</h2>
          <p className="text-gray-600 leading-relaxed mb-6">
            HumansOnly is provided as is. We do not guarantee uptime or availability. 
            We are not responsible for content posted by users.
          </p>

          <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">7. Changes</h2>
          <p className="text-gray-600 leading-relaxed mb-6">
            We may update these terms. Continued use of the service means you accept 
            the updated terms.
          </p>

          <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">Contact</h2>
          <p className="text-gray-600 leading-relaxed">
            Questions about these terms? Email us at <a href="mailto:legal@humansonly.fun" className="text-rose-600 hover:underline">legal@humansonly.fun</a>
          </p>
        </article>

        <footer className="mt-16 pt-8 border-t border-rose-100">
          <div className="flex items-center gap-6 text-sm text-gray-500">
            <Link href="/" className="hover:text-gray-900">Home</Link>
            <Link href="/about" className="hover:text-gray-900">About</Link>
            <Link href="/privacy" className="hover:text-gray-900">Privacy</Link>
          </div>
        </footer>
      </div>
    </div>
  )
}
